### ISSUE TITLE
I can't compile with crystal 0.15

### ISSUE THREAD

**Issue by solisoft** [Sdogruyol/cryload#12]
Here the error log : 
cryload [master●] % crystal build src/cryload.cr --release
Error in ./src/cryload.cr:72: instantiating 'Cryload::Cli:Class#new()'

Cryload::Cli.new
             ^~~

instantiating 'Cryload::Cli#initialize()'

in ./src/cryload/cli.cr:10: instantiating 'Cryload::LoadGenerator:Class#new(String, Int32)'

```
    Cryload::LoadGenerator.new @options[:server], @options[:numbers].to_i
                           ^~~
```

instantiating 'Cryload::LoadGenerator#initialize(String, Int32)'

in ./src/cryload.cr:14: instantiating 'generate_request_channel()'

```
  channel = generate_request_channel
            ^~~~~~~~~~~~~~~~~~~~~~~~
```

in ./src/cryload.cr:21: instantiating 'spawn_request_loop(Channel::Unbuffered(Nil))'

```
  spawn_request_loop channel
  ^~~~~~~~~~~~~~~~~~
```

in ./src/cryload.cr:32: instantiating 'loop()'

```
    loop do
    ^~~~
```

in ./src/cryload.cr:32: instantiating 'loop()'

```
    loop do
    ^~~~
```

in ./src/cryload.cr:33: instantiating 'create_request(HTTP::Client, URI)'

```
      create_request(client, uri)
      ^~~~~~~~~~~~~~
```

in ./src/cryload.cr:61: instantiating 'Cryload::Request:Class#new(HTTP::Client, URI)'

```
  request = Request.new client, uri
                    ^~~
```

instantiating 'Cryload::Request#initialize(HTTP::Client, URI)'

in ./src/cryload/request.cr:22: undefined method 'between?' for Int32

```
  @status_code.between?(200, 300)
               ^~~~~~~~
```
# 

Int32 trace:

  ./src/cryload/request.cr:11

```
      @status_code = response.status_code
      ^
```

  ./src/cryload/request.cr:11

```
      @status_code = response.status_code
                              ^~~~~~~~~~~
```

  macro getter (in /opt/crystal/src/object.cr:221):7

```
      def status_code
          ^~~~~~~~~~~
```

  macro getter (in /opt/crystal/src/object.cr:221):8

```
        @status_code
        ^~~~~~~~~~~~
```

  /opt/crystal/src/http/client/response.cr:14

```
  def initialize(@status_code, @body = nil, @headers : Headers = Headers.new, status_message = nil, @version = "HTTP/1.1", @body_io = nil)
                 ^
```

  /opt/crystal/src/http/client/response.cr:14

```
  def initialize(@status_code, @body = nil, @headers : Headers = Headers.new, status_message = nil, @version = "HTTP/1.1", @body_io = nil)
                 ^~~~~~~~~~~
```

  /opt/crystal/src/http/client/response.cr:14

```
  def initialize(@status_code, @body = nil, @headers : Headers = Headers.new, status_message = nil, @version = "HTTP/1.1", @body_io = nil)
                 ^
```

**Comment by sdogruyol** [comment]
@solisoft thanks for the report.

I've updated to Crystal 0.15.0 and release `0.2.0`.
